[project]
name = "shopping-advisor"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
requires-python = ">=3.10"
dependencies = [
    "httpx>=0.28.1",
    "mcp[cli]>=1.25.0",
    "openai>=2.14.0",
    "pydantic>=2.0.0",
    "python-dotenv>=1.2.1",
]
